version: '3.4'

services:
  employeesapi:
    image: ${DOCKER_REGISTRY-}employeesapi
    build:
      context: .
      dockerfile: EmployeesAPI/Dockerfile
    environment:
      CONNECTION_STRING: server=EmployeesDBService; database=EmployeesDB; Username=postgres; Password=DevPass; 
    networks:
      - development

  db:
    container_name: "EmployeesDBService"
    image: postgres:16.0-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DevPass
      POSTGRES_DB: EmployeesDB
    networks:
      - development

networks:
  development:
